 <?php
 $title = 'Delete Timeline';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($timeline->startdate); ?>' by
     '<?php echo $this->escapeHtml($timeline->headline); ?>'?
 </p>
 <?php
 $url = $this->url('timeline', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="idtimeline" value="<?php echo (int) $timeline->idtimeline; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>