<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My timelines';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('timeline', array('action'=>'add'));?>">Add new timeline</a>
 </p>

 <table class="table">
 <tr>
     <th>Startdate</th>
     <th>Headline</th>
     <th>Type</th>     
     <th>&nbsp;</th>
 </tr>
            
 <?php foreach ($timelines as $timeline) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($timeline->idtimeline);?></td>
     <td><?php echo $this->escapeHtml($timeline->headline);?></td>
     <td><?php echo $this->escapeHtml($timeline->type);?></td>
     <td>
         <a href="<?php echo $this->url('timeline',
             array('action'=>'edit', 'id' => $timeline->idtimeline));?>">Edit</a>
         <a href="<?php echo $this->url('timeline',
             array('action'=>'delete', 'id' => $timeline->idtimeline));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
